# Site settings
title: Freshcocoa
baseurl: ""
url: "http://www.freshcocoa.co.uk"

# Build settings
markdown: kramdown

# People
matt_name: Matthew Wilkinson
matt_title: Developer and Founder
matt_email: matt@freshcocoa.co.uk

# Site Footer
footer_title: Support
support_issue_tracker_title: gitlab.com/Freshcocoa/Trident
support_issue_tracker_url: https://gitlab.com/Freshcocoa/Trident
support_email: matt@freshcocoa.co.uk
support_twitter_username: freshcocoaMatt
support_description: >
  If you have any problems with Trident you can use the public issue tracker and raise an issue, or contact Matt directly with Twitter and Email.
